CREATE TABLE CUSTOMERS (
	ID INTEGER PRIMARY KEY AUTO_INCREMENT,
	NAME VARCHAR(100),
	CPF VARCHAR(11)
);

CREATE TABLE PRODUCTS (
	ID INTEGER PRIMARY KEY AUTO_INCREMENT,
	DESCRIPTION VARCHAR(100),
	UNITY_PRICE NUMERIC(20,2)
);

CREATE TABLE ORDERS (
	ID INTEGER PRIMARY KEY AUTO_INCREMENT,
	CUSTOMERS_ID INTEGER REFERENCES CUSTOMERS(ID),
	DATE_ORDERS TIMESTAMP,
	STATUS VARCHAR(20), 
	TOTAL NUMERIC(20,2)
);

CREATE TABLE ITEN_ORDERS (
	ID INTEGER PRIMARY KEY AUTO_INCREMENT,
	ORDERS_ID INTEGER REFERENCES ORDERS(ID),
	PRODUCTS_ID INTEGER REFERENCES PRODUCTS(ID),
	QUANTITY INTEGER
);