# create database sales;

# use sales;

# show tables;

# select * from user;

CREATE TABLE CUSTOMER (
	ID INTEGER PRIMARY KEY AUTO_INCREMENT,
	NAME VARCHAR(100),
	CPF VARCHAR(11)
);

CREATE TABLE PRODUCT (
	ID INTEGER PRIMARY KEY AUTO_INCREMENT,
	DESCRIPTION VARCHAR(100),
	UNITY_PRICE NUMERIC(20,2)
);

CREATE TABLE ORDERS (
	ID INTEGER PRIMARY KEY AUTO_INCREMENT,
	CUSTOMERS_ID INTEGER REFERENCES CUSTOMERS(ID),
	DATE_ORDERS TIMESTAMP,
	STATUS VARCHAR(20), 
	TOTAL NUMERIC(20,2)
);

CREATE TABLE ITEN_ORDER (
	ID INTEGER PRIMARY KEY AUTO_INCREMENT,
	ORDERS_ID INTEGER REFERENCES ORDERS(ID),
	PRODUCTS_ID INTEGER REFERENCES PRODUCTS(ID),
	QUANTITY INTEGER
);

CREATE TABLE USER (
	ID INTEGER PRIMARY KEY AUTO_INCREMENT,
    USERNAME VARCHAR(50) NOT NULL,
    PASSWORD VARCHAR(255) NOT NULL,
    ADMIN BOOL DEFAULT FALSE
);